server {
    listen 80;
    server_name www.nakedtech.au;

    return 301 https://nakedtech.au$request_uri;
}

server {
    listen 443 ssl;
    server_name www.nakedtech.au;

    ssl_certificate /etc/letsencrypt/live/nakedtech.au/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/nakedtech.au/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    return 301 https://nakedtech.au$request_uri;
}
