const schemaVersion = '1.0'
const websiteUrl = 'https://nakedtech.au'

const serviceAreas = [
  {
    locality: 'Ivanhoe',
    region: 'VIC',
    postcode: '3079',
    country: 'AU',
  },
  {
    locality: 'Eaglemont',
    region: 'VIC',
    postcode: '3084',
    country: 'AU',
  },
]

const sharedBooking = {
  mode: 'request',
  humanConfirmationRequired: true,
  liveAvailability: false,
}

const problemServices = [
  {
    id: 'au.nakedtech.service.wifi_dropouts',
    serviceKey: 'wifi_dropouts',
    name: 'Wi-Fi dropout diagnosis',
    serviceType: 'Home Wi-Fi dropout diagnosis',
    description: 'Separate NBN, router, placement, interference and coverage problems before buying more equipment.',
    path: '/services/wifi-dropouts-ivanhoe/',
    offerType: 'diagnosis',
    pricing: { model: 'fixed', currency: 'AUD', amount: 190, includesGst: true, requiresQuote: false, displayText: '$190 fixed incl. GST' },
    hardware: { purchaseModel: 'not_required' },
    presentation: {
      group: 'problem',
      navGroup: 'fix',
      navTitle: 'Wi-Fi keeps dropping',
      navDescription: 'Find the cause before buying hardware',
      title: 'Wi-Fi keeps dropping out',
      cta: 'See the diagnosis',
      iconPath: 'M8.111 16.404a5.5 5.5 0 017.778 0M12 20h.01m-7.08-7.071c3.904-3.905 10.236-3.905 14.141 0M1.394 9.393c5.857-5.857 15.355-5.857 21.213 0',
    },
  },
  {
    id: 'au.nakedtech.service.slow_computer',
    serviceKey: 'slow_computer',
    name: 'Slow Computer Performance Assessment',
    serviceType: 'Slow computer performance assessment and Windows lifecycle advice',
    description: 'Understand what is slowing it down and whether fixing, upgrading or replacing it is the sensible next step.',
    path: '/services/slow-computer-help-ivanhoe/',
    offerType: 'assessment',
    pricing: { model: 'fixed', currency: 'AUD', amount: 190, includesGst: true, requiresQuote: false, displayText: '$190 fixed incl. GST' },
    hardware: { purchaseModel: 'depends_on_scope' },
    presentation: {
      group: 'problem',
      navGroup: 'fix',
      navTitle: 'Computer running slowly',
      navDescription: 'Decide whether to fix, upgrade or replace',
      title: 'Computer running slowly',
      cta: 'See the assessment',
      iconPath: 'M9.75 17L9 20l-1 1h8l-1-1-.75-3M3 13h18M5 17h14a2 2 0 002-2V5a2 2 0 00-2-2H5a2 2 0 00-2 2v10a2 2 0 002 2z',
    },
  },
  {
    id: 'au.nakedtech.service.scam_security',
    serviceKey: 'scam_security',
    name: 'Scam & account-security assessment',
    serviceType: 'Scam and account security assessment',
    description: 'Calmly review what happened, inspect the affected device and prioritise the next safe actions.',
    path: '/services/scam-security-help-ivanhoe/',
    offerType: 'assessment',
    pricing: { model: 'fixed', currency: 'AUD', amount: 250, includesGst: true, requiresQuote: false, displayText: '$250 fixed incl. GST' },
    hardware: { purchaseModel: 'not_required' },
    presentation: {
      group: 'problem',
      navGroup: 'fix',
      navTitle: 'Scam or account concern',
      navDescription: 'Calm onsite security help',
      title: 'Scam or account concern',
      cta: 'Get scam & security help',
      iconPath: 'M12 2l7 4v5c0 5-3.5 9.5-7 11-3.5-1.5-7-6-7-11V6l7-4zm-3 10l2 2 4-4',
    },
  },
  {
    id: 'au.nakedtech.service.virus_malware',
    serviceKey: 'virus_malware',
    name: 'Virus & Malware Diagnosis and Removal Visit',
    serviceType: 'Personal computer virus and malware diagnosis and removal',
    description: 'Diagnose suspicious computer behaviour, complete safe user-level removal where practical and leave with clear written next steps.',
    path: '/services/virus-malware-help-ivanhoe/',
    offerType: 'diagnosis_and_remediation',
    pricing: { model: 'fixed', currency: 'AUD', amount: 250, includesGst: true, requiresQuote: false, displayText: '$250 fixed incl. GST' },
    hardware: { purchaseModel: 'not_required' },
    presentation: {
      group: 'problem',
      navGroup: 'fix',
      navTitle: 'Possible virus or malware',
      navDescription: 'Diagnose and safely remove what we can',
      title: 'Possible virus or malware',
      cta: 'See the diagnosis visit',
      iconPath: 'M12 2l7 4v5c0 5-3.5 9.5-7 11-3.5-1.5-7-6-7-11V6l7-4zm0 5v5m0 4h.01',
    },
  },
  {
    id: 'au.nakedtech.service.new_computer_setup',
    serviceKey: 'new_computer_setup',
    name: 'Standard Windows Move',
    serviceType: 'New computer setup and Windows data transfer',
    description: 'Move one user and up to 250 GB from a healthy Windows computer to a new Windows 11 computer.',
    path: '/services/new-computer-setup-data-transfer-ivanhoe/',
    offerType: 'setup',
    pricing: { model: 'fixed', currency: 'AUD', amount: 550, includesGst: true, requiresQuote: false, displayText: '$550 fixed incl. GST' },
    hardware: { purchaseModel: 'customer_supplied' },
    presentation: {
      group: 'problem',
      navGroup: 'setup',
      navTitle: 'Setting up a new computer',
      navDescription: 'Windows setup & data transfer',
      title: 'Setting up a new computer',
      cta: 'Check whether it fits',
      iconPath: 'M7 7h10M7 7l3-3M7 7l3 3m7 7H7m10 0l-3-3m3 3l-3 3',
    },
  },
  {
    id: 'au.nakedtech.service.printer_help',
    serviceKey: 'printer_help',
    name: 'Printer Troubleshooting Visit',
    serviceType: 'Household printer troubleshooting',
    description: 'Troubleshoot one existing printer with one primary device and get a clear next step if hardware or provider action is needed.',
    path: '/services/printer-help-ivanhoe/',
    offerType: 'troubleshooting',
    pricing: { model: 'fixed', currency: 'AUD', amount: 190, includesGst: true, requiresQuote: false, displayText: '$190 fixed incl. GST' },
    hardware: { purchaseModel: 'customer_supplied' },
    presentation: {
      group: 'problem',
      navGroup: 'fix',
      navTitle: 'Printer won’t print or scan',
      navDescription: 'Troubleshoot one existing printer',
      title: 'Printer won’t print or scan',
      cta: 'See the printer visit',
      iconPath: 'M6 9V4h12v5M6 17H4a2 2 0 01-2-2v-4a2 2 0 012-2h16a2 2 0 012 2v4a2 2 0 01-2 2h-2m-12-3h12v6H6v-6zm12-2h.01',
    },
  },
  {
    id: 'au.nakedtech.service.email_help',
    serviceKey: 'email_help',
    name: 'Personal Email Troubleshooting Visit',
    serviceType: 'Personal email troubleshooting',
    description: 'Troubleshoot one existing personal email account on one supported device, with credentials kept under your control.',
    path: '/services/email-help-ivanhoe/',
    offerType: 'troubleshooting',
    pricing: { model: 'fixed', currency: 'AUD', amount: 190, includesGst: true, requiresQuote: false, displayText: '$190 fixed incl. GST' },
    hardware: { purchaseModel: 'not_required' },
    presentation: {
      group: 'problem',
      navGroup: 'fix',
      navTitle: 'Email stopped working',
      navDescription: 'One personal account on one device',
      title: 'Email stopped working',
      cta: 'See the email visit',
      iconPath: 'M3 8l7.89 5.26a2 2 0 002.22 0L21 8m-18 8V6a2 2 0 012-2h14a2 2 0 012 2v10a2 2 0 01-2 2H5a2 2 0 01-2-2z',
    },
  },
  {
    id: 'au.nakedtech.service.new_printer_setup',
    serviceKey: 'new_printer_setup',
    name: 'New Printer Setup Visit',
    serviceType: 'New household printer setup',
    description: 'Get one new household printer connected to one primary device, tested and ready for everyday use.',
    path: '/services/new-printer-setup-ivanhoe/',
    offerType: 'setup',
    pricing: { model: 'fixed', currency: 'AUD', amount: 250, includesGst: true, requiresQuote: false, displayText: '$250 fixed incl. GST' },
    hardware: { purchaseModel: 'customer_supplied' },
    presentation: {
      group: 'problem',
      navGroup: 'setup',
      navTitle: 'Setting up a new printer',
      navDescription: 'Unbox, connect and test one printer',
      title: 'Setting up a new printer',
      cta: 'See the setup visit',
      iconPath: 'M6 9V4h12v5M6 17H4a2 2 0 01-2-2v-4a2 2 0 012-2h16a2 2 0 012 2v4a2 2 0 01-2 2h-2m-12-3h12v6H6v-6zm12-2h.01',
    },
  },
  {
    id: 'au.nakedtech.service.backup_setup',
    serviceKey: 'backup_setup',
    name: 'Computer Backup Setup Visit',
    serviceType: 'Personal computer backup setup and restore-readiness check',
    description: 'Configure one automatic local or cloud backup for one computer, test a sample restore and leave with a clear checking routine.',
    path: '/services/backup-setup-ivanhoe/',
    offerType: 'setup',
    pricing: { model: 'fixed', currency: 'AUD', amount: 250, includesGst: true, requiresQuote: false, displayText: '$250 fixed incl. GST' },
    hardware: { purchaseModel: 'depends_on_scope' },
    presentation: {
      group: 'problem',
      navGroup: 'setup',
      navTitle: 'Backups are not set up',
      navDescription: 'Configure, test and understand one backup',
      title: 'Backups are not set up',
      cta: 'See the backup visit',
      iconPath: 'M4 7v10a2 2 0 002 2h12a2 2 0 002-2V7M8 11l4 4 4-4m-4 4V3',
    },
  },
  {
    id: 'au.nakedtech.service.mobile_setup',
    serviceKey: 'mobile_setup',
    name: 'Phone & Tablet Setup and Migration Visit',
    serviceType: 'Personal phone and tablet setup and same-ecosystem migration',
    description: 'Set up one new phone or tablet and move supported data from one working device while you keep control of accounts and credentials.',
    path: '/services/phone-tablet-setup-migration-ivanhoe/',
    offerType: 'setup',
    pricing: { model: 'fixed', currency: 'AUD', amount: 390, includesGst: true, requiresQuote: false, displayText: '$390 fixed incl. GST' },
    hardware: { purchaseModel: 'customer_supplied' },
    presentation: {
      group: 'problem',
      navGroup: 'setup',
      navTitle: 'Setting up a phone or tablet',
      navDescription: 'Same-ecosystem setup and supported transfer',
      title: 'Setting up a phone or tablet',
      cta: 'See the setup visit',
      iconPath: 'M7 2h10a2 2 0 012 2v16a2 2 0 01-2 2H7a2 2 0 01-2-2V4a2 2 0 012-2zm3 3h4m-3 14h2',
    },
  },
  {
    id: 'au.nakedtech.service.password_safety_control',
    serviceKey: 'password_safety_control',
    name: 'Password Safety & Control Visit',
    serviceType: 'Personal password manager setup',
    description: 'Set up one supported personal password system across a computer and phone, with a practical recovery plan kept in your hands.',
    path: '/services/password-manager-setup-ivanhoe/',
    offerType: 'setup',
    pricing: { model: 'fixed', currency: 'AUD', amount: 390, includesGst: true, requiresQuote: false, displayText: '$390 fixed incl. GST' },
    hardware: { purchaseModel: 'depends_on_scope' },
    presentation: {
      group: 'problem',
      navGroup: 'setup',
      navTitle: 'Passwords are scattered',
      navDescription: 'Set up one system you control',
      title: 'Passwords reused, written down or scattered',
      cta: 'See the password visit',
      iconPath: 'M12 11c1.657 0 3-1.343 3-3s-1.343-3-3-3 1.343-3 3 1.343 3 3 3zm0 0v4m-7 5h14a2 2 0 002-2v-5a2 2 0 00-2-2H5a2 2 0 00-2 2v5a2 2 0 002 2z',
    },
  },
]

const projectServices = [
  {
    id: 'au.nakedtech.service.full_strip',
    serviceKey: 'full-strip',
    name: 'The Full Strip',
    serviceType: 'Whole-home Mesh Wi-Fi',
    description: 'Diagnose weak spots and install enterprise-grade Mesh Wi-Fi for more reliable coverage throughout your home.',
    path: '/services/full-strip/',
    offerType: 'project',
    pricing: { model: 'range', currency: 'AUD', minimum: 900, maximum: 1800, includesGst: true, requiresQuote: true, displayText: '$900–$1,800 incl. GST' },
    hardware: { purchaseModel: 'additional_at_cost' },
    presentation: {
      group: 'project',
      priceLine: 'Fixed project quote + hardware at cost',
      iconPath: 'M8.111 16.404a5.5 5.5 0 017.778 0M12 20h.01m-7.08-7.071c3.904-3.905 10.236-3.905 14.141 0M1.394 9.393c5.857-5.857 15.355-5.857 21.213 0',
    },
  },
  {
    id: 'au.nakedtech.service.power_pose',
    serviceKey: 'power-pose',
    name: 'The Power Pose',
    serviceType: 'Home office setup',
    description: 'Turn a cluttered desk into a cleaner, better-connected workspace with cable management, monitor mounting and video-call lighting.',
    path: '/services/power-pose/',
    offerType: 'project',
    pricing: { model: 'fixed', currency: 'AUD', amount: 350, includesGst: true, requiresQuote: false, displayText: '$350 incl. GST' },
    hardware: { purchaseModel: 'additional_at_cost' },
    presentation: {
      group: 'project',
      priceLine: 'Fixed project price',
      iconPath: 'M13 10V3L4 14h7v7l9-11h-7z',
    },
  },
]

const services = [...problemServices, ...projectServices].map((service) => ({
  ...service,
  status: 'active',
  canonicalUrl: `${websiteUrl}${service.path}`,
  deliveryMethod: 'in_home',
  serviceAreas,
  booking: sharedBooking,
}))

const publicServices = services.map(({ path, presentation, ...service }) => service)

module.exports = {
  schemaVersion,
  serviceAreas,
  services,
  byKey: Object.fromEntries(services.map((service) => [service.serviceKey, service])),
  public: {
    schemaVersion,
    publisher: {
      name: 'Naked Tech',
      url: websiteUrl,
      entityId: `${websiteUrl}/#business`,
    },
    links: {
      self: `${websiteUrl}/services.json`,
      website: `${websiteUrl}/services/`,
      terms: `${websiteUrl}/terms/`,
      privacy: `${websiteUrl}/privacy/`,
    },
    services: publicServices,
  },
}
